name: Production Deployment

on:
  push:
  workflow_dispatch:
  
jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - shell: pwsh
      run: Write-Host 'Running development deployment'
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - shell: pwsh
      run: |
        Install-Module -Name AWS.Tools.EC2 -Force
        Get-EC2Instance
