name: Production Deployment

on:
  push:
  workflow_dispatch:
  
jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    environment: production2
    steps:
    - shell: pwsh
      run: Write-Host 'Running production deployment'
